### ISSUE TITLE
Better highlight the requirement for setting rpcUrl when non ethers/ viemWallet signers are used

### ISSUE THREAD

**Issue by joepegler** [bcnmy/docs#202]
There are certain circumstances where the rpcUrl will be picked up when custom signers are used, but for the most part it's safe to say they will not be ingested during createSmartAccountClient unless the signer is one of those two signer types (viemWallet or ethers.Signer). 

Because of this we should make it better known that rpcUrl is an available property in the config, particularly in the sections for the custom signers: 
![image](https://github.com/bcnmy/docs/assets/4627587/938b9609-74d6-47fb-bbdc-0ce3fb6452db)

If rpcUrl is not provided then a default public rpc will be used - which will likely be heavily throttled and can often silently fail - so the ramifications can be nasty for end users if the dev isn't paying attention.

**Comment by himanshugarg06** [comment]
Add the following in the Usage code here - https://docs.biconomy.io/Account/methods#createsmartaccountclient

```ts
const smartAccount = await createSmartAccountClient({
  signer,
  bundlerUrl: "", // <-- Read about this at https://docs.biconomy.io/dashboard#bundler-url
  biconomyPaymasterApiKey: "", // <-- Read about at https://docs.biconomy.io/dashboard/paymaster
  rpcUrl: "", // This is an optional param, Its advised to pass RPC url in case of custom signers such as privy, dynamic etc. If 
            // rpcUrl is not provided then a default public rpc will be used - which will likely be heavily throttled and can often 
           // silently fail
});
```

we can mention the same in description of the rpcUrl param below 

and add rpcUrl in the smart account creation for all signers.
