### ISSUE TITLE
Bundler API docs update

### ISSUE THREAD

**Issue by himanshugarg06** [bcnmy/docs#205]

**Comment by himanshugarg06** [comment]
# Bundler Documentation

[https://docs.biconomy.io/Bundler/](https://docs.biconomy.io/bundler)

Bundler can be used in the following ways:

1. In integration with Biconomy smart account SDK [[package](https://www.npmjs.com/package/@biconomy/account)](https://www.npmjs.com/package/@biconomy/account)
    
    ```jsx
    import { createSmartAccountClient, createBundler } from "**@biconomy/account**";
    
    const userOpReceiptMaxDurationIntervals: { [key in number]?: number } = {
      [80001]: 60000,
    };
    
    const bundler = await createBundler({
      bundlerUrl: "", // <-- Read about this at https://docs.biconomy.io/dashboard#bundler-url
      userOpReceiptMaxDurationIntervals,
    });
    ```
    
2. Using the [[Bundler package](https://www.npmjs.com/package/@biconomy/bundler)](https://www.npmjs.com/package/@biconomy/bundler) 
https://bcnmy.github.io/biconomy-client-sdk/classes/Bundler.html#create
    
    ```jsx
    import { create } from "**@biconomy/bundler**";
    
    const userOpReceiptMaxDurationIntervals: { [key in number]?: number } = {
      [80001]: 60000,
    };
    
    const bundler = await create({
      bundlerUrl: "", // <-- Read about this at https://docs.biconomy.io/dashboard#bundler-url
      userOpReceiptMaxDurationIntervals,
    });
    ```
    
3. Via the APIs  (platform independent) - can exist as it is but to get exact request and response structure, API documentation like postman or swagger can be used.

**Open Question**

- Integration and methods pages will look *different* depending on whether we want to go ahead with 1 or 2. which package to use here? @NunoFilipeSantos @Graeme-Code @shruti892
- API documentation for bundler and similarly for paymaster

**ToDos**

- Update tsdocs to reflect proper documentation for bundler methods
- Update tsDocs add explanation for params like - [[userOpReceiptIntervals](https://bcnmy.github.io/biconomy-client-sdk/classes/Bundler.html#UserOpReceiptIntervals)](https://bcnmy.github.io/biconomy-client-sdk/classes/Bundler.html#UserOpReceiptIntervals) and other parameters
- add gas estimate and sendUserOp example on the bundler integration page in docs.
- add and refactor remaining bundler methods which are not listed in the docs.
- Mention different receipt format for L1 & L2s in the [[APIs](https://docs.biconomy.io/Bundler/api/get-useroperation-receipt#response)](https://docs.biconomy.io/Bundler/api/get-useroperation-receipt#response) @arcticfloyd1984 to help with the information. (Great if we have Postman examples)
- Update validAfter, validUntil types in the [[response](https://docs.biconomy.io/Bundler/api/estimate-useroperation-gas#response)](https://docs.biconomy.io/Bundler/api/estimate-useroperation-gas#response) in the docs, this can be automated with API documentation.

**Comment by himanshugarg06** [comment]
but for sdk there is a method already existing in the accounts package as mentioned above. we would want sdk users to use this method?
import { createSmartAccountClient, createBundler } from "**@biconomy/account**";

**Comment by joepegler** [comment]
Yeah they can for sure, it's just not relevant to this part of the documentation

![image](https://github.com/bcnmy/docs/assets/4627587/e019c85a-72f6-4611-afd6-5bce6eca8f76)

**Comment by himanshugarg06** [comment]
https://github.com/bcnmy/docs/pull/221

**Comment by himanshugarg06** [comment]
StateOverrideSet in https://bcnmy.github.io/biconomy-client-sdk/classes/Bundler.html#estimateUserOpGas

**Comment by himanshugarg06** [comment]
Mention different receipt format for L1 & L2s in the [[APIs](https://docs.biconomy.io/Bundler/api/get-useroperation-receipt#response)](https://docs.biconomy.io/Bundler/api/get-useroperation-receipt#response) @arcticfloyd1984 to help with the information. (Great if we have Postman examples)

mention stateOverrideSet usage in the API if needed - https://docs.biconomy.io/Bundler/api/estimate-useroperation-gas
