### ISSUE TITLE
Add smart account methods 

### ISSUE THREAD

**Issue by joepegler** [bcnmy/docs#215]
### How could we improve the Biconomy documentation site?

Document [smartAccount.deploy()](https://bcnmy.github.io/biconomy-client-sdk/classes/BiconomySmartAccountV2.html#deploy) for upcoming release

Document [smartAccount.getBalances(tokenAddresses)](https://bcnmy.github.io/biconomy-client-sdk/classes/BiconomySmartAccountV2.html#getBalances) for upcoming release

Document [smartAccount.getSupportedTokens()](https://bcnmy.github.io/biconomy-client-sdk/classes/BiconomySmartAccountV2.html#getSupportedTokens) for upcoming release

**Comment by himanshugarg06** [comment]
@joepegler let me know once these methods are added.
