### ISSUE TITLE
Better explain simulation types and when to use them

### ISSUE THREAD

**Issue by joepegler** [bcnmy/docs#241]
### How could we improve the Biconomy documentation site?

SimulationType === "validation" = no latency, no useful feedback: (production mode). SimulationType === "validation_and_execution" = increased latency, provides useful errors (developer mode).

Multiple users are still highlighting issues that could be resolved if they'd known and availed of our `validation_and_execution` mode, most recently Kwenta.

**Comment by himanshugarg06** [comment]
https://docs.biconomy.io/Account/methods#sendtransaction- Have added more details.
