### ISSUE TITLE
[Feedback] Page: /quickstart

### ISSUE THREAD

**Issue by yashmadhwal** [bcnmy/docs#275]
### How could we improve the Biconomy documentation site?

Hi! The full code should be this:
const userOpResponse = await smartAccount.sendTransaction({
        to: nftAddress,
        data: nftData,
      });

    const { waitForTxHash } = await smartAccount.sendTransaction({
        to: nftAddress,
        data: nftData,
    });

    const { transactionHash } = await waitForTxHash();
    console.log("transactionHash", transactionHash);

    const userOpReceipt = await userOpResponse.wait();
    if (userOpReceipt.success == "true") {
        console.log("UserOp receipt", userOpReceipt);
        console.log("Transaction receipt", userOpReceipt.receipt);
    }

**Comment by himanshugarg06** [comment]
Have updated this, thank you for reporting.
