### ISSUE TITLE
[Feedback] : `chainId` wrong in Docs

### ISSUE THREAD

**Issue by pratham-bhatnagar** [bcnmy/docs#287]
### How could we improve the Biconomy documentation site?

https://github.com/bcnmy/docs/blob/master/docs/Account/signers/web3auth.md

Polygon Amoy chainId is not right here

![image](https://github.com/bcnmy/docs/assets/84272138/d056a761-4335-421e-a380-a96ed4bd5f39)

Should be `0x13882` instead

**Comment by B-Venkatesh7210** [comment]
Thank you @pratham-bhatnagar , we have changed the chain id.
