### ISSUE TITLE
[Feedback] Page: /tutorials/sendGasless

### ISSUE THREAD

**Issue by 3ill** [bcnmy/docs#308]
### How could we improve the Biconomy documentation site?

Lacks an example demonstrating a key use case. It fails to illustrate how one interacts with a smart contract, such as invoking a gasless write operation.

**Comment by himanshugarg06** [comment]
All examples in the docs are mostly for write operation. You can create the data like this - https://docs.biconomy.io/quickstart#3-execute-your-first-transaction-
