### ISSUE TITLE
Missing method.

### ISSUE THREAD

**Issue by iamonuwa** [bcnmy/docs#73]
`.address` appears not to be in the sdk. What is available is the `.getSmartAccountAddress()`

const biconomyAccount = new BiconomySmartAccount(biconomySmartAccountConfig)
const biconomySmartAccount =  await biconomyAccount.init()
console.log("owner: ", biconomySmartAccount.owner)
console.log("address: ", biconomySmartAccount.address)

https://docs.biconomy.io/docs/Biconomy%20AA%20Stack/Account/initialization

**Comment by Rahat-ch** [comment]
Hey @iamonuwa in the latest version of the the sdk the method is .getAccountAddress()

With the method you are mentioning this is referring to Account V1 https://docs.biconomy.io/docs/category/smart-account-v1
