### ISSUE TITLE
Add error messages explanation to docs.

### ISSUE THREAD

**Issue by iamonuwa** [bcnmy/docs#89]
Would be great to have error messages explained on the docs

1. `{"code": 502, "data": undefined, "message": "An invalid response was received from the upstream server"}`

**Comment by NunoFilipeSantos** [comment]
@iamonuwa do you mean adding them [here](https://docs.biconomy.io/troubleshooting/commonerrors)?

**Comment by iamonuwa** [comment]
This has been resolved internally
