### ISSUE TITLE
Add Algolia search, OpenAPI plugin and minor improvements

### ISSUE THREAD

**Issue by AmanRaj1608** [bcnmy/docs#9]
- Add Algolia search option https://docusaurus.io/docs/search
- Add swagger API for the API section using https://github.com/PaloAltoNetworks/docusaurus-openapi-docs
- In the `quick explore > setup node cli` section
	- We should mention what all contracts they should verify for doing transactions, only adding paymaster url will not work. 
	- Or maybe we can have a section to do trx and then tell why they get that error.
- Add common error page what Talha had created previously https://www.notion.so/biconomy/Troubleshooting-Guide-778da8ec6c104ab08c5ff9313cdc0091

**Comment by yashdev9274** [comment]
Hey @AmanRaj1608 If no-one is assigned to this issue then I would love to work on it.

**Comment by Rahat-ch** [comment]
Issues addressed swagger will be addressed with api updates
